### ISSUE TITLE
BDD tests

### ISSUE THREAD

**Issue by dawe00** [BME-MIT-IET/iet-hf-2022-v-dqw4w9wgxcq-1#1]
# Az alábbi függvényekhez BDD tesztek elkészítése:

## processor\model\impl\TemplateCallImpl.java (Dawe)
applyArguments(MultivaluedMap<String, String> queryParams)
*applyDefaults()
*getArgument(Property predicate)
getArgument(String varName, RDFNode object)
*getArgumentProperty(Property predicate)
arg(Parameter param, RDFNode value)
arg(Resource arg)
validateOptionals()
getQuerySolutionMap()

## processor\model\impl\TemplateImpl.java (Dawe)
*canWrap(Node node, EnhGraph eg)
getMatch()
*getFragmentTemplate()
*getQuery()
*getUpdate()
*getPriority()
*getParameters()
getLocalParameters()
*getParameterMap()
*getLanguages()
getLanguages(Template template, Property property)
*getLoadClass()
*getCacheControl()
getSuperTemplates(Template template)
*getSelfOrSuperWithProperty(Property property)

## processor\util\Skolomizer.java (Laci)
build(Model model)
build(Resource resource)

## processor\util\TemplateMatcher.java (Laci)
match(URI uri, URI base)
match(Ontology ontology, CharSequence path, int level)
match(Ontology ontology, CharSequence path)

**Comment by ghost** [comment]
TemplateMatcher osztály BDD tesztje #6

**Comment by ghost** [comment]
TemplateMatcher osztály BDD tesztjének javítása #9

**Comment by ghost** [comment]
Skolemizer osztály BDD tesztjei #10

**Comment by ghost** [comment]
Rename TemplateMatcher and Skolemizer tests #11

**Comment by dawe00** [comment]
TemplateCallImpl Cucumber tests #12

**Comment by dawe00** [comment]
TemplateImpl Cucumber tests #13

**Comment by ghost** [comment]
Finish the exercise #15

**Comment by ghost** [comment]
BDD tesztek készek és működőképesek
