### ISSUE TITLE
Manual tests

### ISSUE THREAD

**Issue by dawe00** [BME-MIT-IET/iet-hf-2022-v-dqw4w9wgxcq-1#2]
Manuális tesztek elvégzése az alábbi fájlokon:

processor\model\impl\TemplateCallImpl.java
processor\model\impl\TemplateImpl.java

processor\util\RDFNodeFactory.java
processor\util\Skolomizer.java
processor\util\TemplateMatcher.java

**Comment by botondklenk** [comment]
A manuális teszt az egész programra vonatkozik így nem csak adott fájlokon csináltam meg.
