### ISSUE TITLE
SonarCloud setup

### ISSUE THREAD

**Issue by dawe00** [BME-MIT-IET/iet-hf-2022-v-dqw4w9wgxcq-1#3]
Az alábbi fájlok tesztelése SonarCloud segítségével:

processor\model\impl\TemplateCallImpl.java
processor\model\impl\TemplateImpl.java

processor\util\RDFNodeFactory.java
processor\util\Skolomizer.java
processor\util\TemplateMatcher.java

**Comment by lyndise** [comment]
#5 és #7 PR-el sikeresen bekerült a SonarCloud

**Comment by lyndise** [comment]
#8 PR-ben látható a dokumentációval és javításokkal kapcsolatos commitok

**Comment by lyndise** [comment]
#14 PR-ben további felfedezett code smell javítások
